stages:
    - test
    - build
    - deploy

push_to_github:
    stage: build
    variables:
        GIT_STRATEGY: none
    script:
        - rm -rf ./*
        - rm -rf .git
        - git clone --mirror $CI_REPOSITORY_URL .
        - git remote add github $GITHUB_URL_AND_KEY
        - git config --global user.email "contact@duniter.org"
        - git config --global user.name "Duniter"
        - cat packed-refs
        - rm -rf refs/pull
        - bash -c "git push --force --mirror github 2>&1 | grep -v duniter-gitlab; echo $?"
