stages:
    - github-sync
    - build
    - publish
#Stage name is used in the tag to download artifacts
README:
  stage: build
  artifacts:
    name: README
    paths:
      - README.md
  script:
    - ls README.md
  only:
    - tags
  tags:
    - github

push_realease_to_github:
    stage: publish
    script:
      - export GITHUB_TOKEN=${GITHUB_TOKEN}
      - echo "Creating a new release in github"
      - github-release release --user duniter --repo gitlab --tag "${CI_BUILD_TAG}"
      - echo "Uploading the artifacts into github"
      - bash -c 'github-release upload --user duniter --repo gitlab --tag "${CI_BUILD_TAG}" --name "README.md" --file ./README.md'
    only:
      - tags
    tags:
      - github

push_to_github:
    stage: github-sync
    variables:
        GIT_STRATEGY: none
    script:
        - rm -rf ./*
        - rm -rf .git
        - git clone --mirror $CI_REPOSITORY_URL .
        - git remote add github $GITHUB_URL_AND_KEY
        - git config --global user.email "contact@duniter.org"
        - git config --global user.name "Duniter"
        # Job would fail if we don't remove refs about pull requests
        - bash -c "cat packed-refs | grep -v 'refs/pull' > packed-refs-new; echo 'Removed pull refs.'"
        - mv packed-refs-new packed-refs
        - bash -c "git push --force --mirror github 2>&1 | grep -v duniter-gitlab; echo $?"
    tags:
      - github
      
enforce_readme:
    stage: github-sync
    variables:
        GIT_STRATEGY: none
    script:
      - rm -rf ./*
      - rm -rf .git
      - git clone $GITHUB_URL_AND_KEY .
      - git config --global user.email "contact@duniter.org"
      - git config --global user.name "Duniter"
      - git checkout master
      - cat .github/github_disclaimer.md > README.md.new
      - cat README.md >> README.md.new
      - cp README.md.new README.md
      - git commit -am "Enforce github readme"
      - git push --force origin master
    tags:
      - github